/*
 * This file is generated by jOOQ.
 */
package sk.catheaven.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import sk.catheaven.model.tables.Accounts;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountsRecord extends UpdatableRecordImpl<AccountsRecord> implements Record7<Long, String, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.accounts.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.accounts.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.accounts.screen_name</code>.
     */
    public void setScreenName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.accounts.screen_name</code>.
     */
    public String getScreenName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.accounts.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.accounts.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.accounts.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.accounts.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.accounts.followers_count</code>.
     */
    public void setFollowersCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.accounts.followers_count</code>.
     */
    public Integer getFollowersCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.accounts.friends_count</code>.
     */
    public void setFriendsCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.accounts.friends_count</code>.
     */
    public Integer getFriendsCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.accounts.statuses_count</code>.
     */
    public void setStatusesCount(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.accounts.statuses_count</code>.
     */
    public Integer getStatusesCount() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Accounts.ACCOUNTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Accounts.ACCOUNTS.SCREEN_NAME;
    }

    @Override
    public Field<String> field3() {
        return Accounts.ACCOUNTS.NAME;
    }

    @Override
    public Field<String> field4() {
        return Accounts.ACCOUNTS.DESCRIPTION;
    }

    @Override
    public Field<Integer> field5() {
        return Accounts.ACCOUNTS.FOLLOWERS_COUNT;
    }

    @Override
    public Field<Integer> field6() {
        return Accounts.ACCOUNTS.FRIENDS_COUNT;
    }

    @Override
    public Field<Integer> field7() {
        return Accounts.ACCOUNTS.STATUSES_COUNT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getScreenName();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Integer component5() {
        return getFollowersCount();
    }

    @Override
    public Integer component6() {
        return getFriendsCount();
    }

    @Override
    public Integer component7() {
        return getStatusesCount();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getScreenName();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Integer value5() {
        return getFollowersCount();
    }

    @Override
    public Integer value6() {
        return getFriendsCount();
    }

    @Override
    public Integer value7() {
        return getStatusesCount();
    }

    @Override
    public AccountsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AccountsRecord value2(String value) {
        setScreenName(value);
        return this;
    }

    @Override
    public AccountsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public AccountsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public AccountsRecord value5(Integer value) {
        setFollowersCount(value);
        return this;
    }

    @Override
    public AccountsRecord value6(Integer value) {
        setFriendsCount(value);
        return this;
    }

    @Override
    public AccountsRecord value7(Integer value) {
        setStatusesCount(value);
        return this;
    }

    @Override
    public AccountsRecord values(Long value1, String value2, String value3, String value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountsRecord
     */
    public AccountsRecord() {
        super(Accounts.ACCOUNTS);
    }

    /**
     * Create a detached, initialised AccountsRecord
     */
    public AccountsRecord(Long id, String screenName, String name, String description, Integer followersCount, Integer friendsCount, Integer statusesCount) {
        super(Accounts.ACCOUNTS);

        setId(id);
        setScreenName(screenName);
        setName(name);
        setDescription(description);
        setFollowersCount(followersCount);
        setFriendsCount(friendsCount);
        setStatusesCount(statusesCount);
    }
}
