/*
 * This file is generated by jOOQ.
 */
package sk.catheaven.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import sk.catheaven.model.tables.ConspiracyTheories;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConspiracyTheoriesRecord extends UpdatableRecordImpl<ConspiracyTheoriesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.conspiracy_theories.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.conspiracy_theories.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.conspiracy_theories.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.conspiracy_theories.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ConspiracyTheories.CONSPIRACY_THEORIES.ID;
    }

    @Override
    public Field<String> field2() {
        return ConspiracyTheories.CONSPIRACY_THEORIES.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public ConspiracyTheoriesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ConspiracyTheoriesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ConspiracyTheoriesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConspiracyTheoriesRecord
     */
    public ConspiracyTheoriesRecord() {
        super(ConspiracyTheories.CONSPIRACY_THEORIES);
    }

    /**
     * Create a detached, initialised ConspiracyTheoriesRecord
     */
    public ConspiracyTheoriesRecord(Integer id, String name) {
        super(ConspiracyTheories.CONSPIRACY_THEORIES);

        setId(id);
        setName(name);
    }
}
