/*
 * This file is generated by jOOQ.
 */
package sk.catheaven.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import sk.catheaven.model.tables.HashtagConspiracyTheory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HashtagConspiracyTheoryRecord extends UpdatableRecordImpl<HashtagConspiracyTheoryRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.hashtag_conspiracy_theory.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.hashtag_conspiracy_theory.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.hashtag_conspiracy_theory.hashtag_id</code>.
     */
    public void setHashtagId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.hashtag_conspiracy_theory.hashtag_id</code>.
     */
    public Integer getHashtagId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>public.hashtag_conspiracy_theory.conspiracy_theory_id</code>.
     */
    public void setConspiracyTheoryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.hashtag_conspiracy_theory.conspiracy_theory_id</code>.
     */
    public Integer getConspiracyTheoryId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return HashtagConspiracyTheory.HASHTAG_CONSPIRACY_THEORY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return HashtagConspiracyTheory.HASHTAG_CONSPIRACY_THEORY.HASHTAG_ID;
    }

    @Override
    public Field<Integer> field3() {
        return HashtagConspiracyTheory.HASHTAG_CONSPIRACY_THEORY.CONSPIRACY_THEORY_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getHashtagId();
    }

    @Override
    public Integer component3() {
        return getConspiracyTheoryId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getHashtagId();
    }

    @Override
    public Integer value3() {
        return getConspiracyTheoryId();
    }

    @Override
    public HashtagConspiracyTheoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public HashtagConspiracyTheoryRecord value2(Integer value) {
        setHashtagId(value);
        return this;
    }

    @Override
    public HashtagConspiracyTheoryRecord value3(Integer value) {
        setConspiracyTheoryId(value);
        return this;
    }

    @Override
    public HashtagConspiracyTheoryRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HashtagConspiracyTheoryRecord
     */
    public HashtagConspiracyTheoryRecord() {
        super(HashtagConspiracyTheory.HASHTAG_CONSPIRACY_THEORY);
    }

    /**
     * Create a detached, initialised HashtagConspiracyTheoryRecord
     */
    public HashtagConspiracyTheoryRecord(Integer id, Integer hashtagId, Integer conspiracyTheoryId) {
        super(HashtagConspiracyTheory.HASHTAG_CONSPIRACY_THEORY);

        setId(id);
        setHashtagId(hashtagId);
        setConspiracyTheoryId(conspiracyTheoryId);
    }
}
