/*
 * This file is generated by jOOQ.
 */
package sk.catheaven.model.tables.records;


import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import sk.catheaven.model.tables.StHexagongrid;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StHexagongridRecord extends TableRecordImpl<StHexagongridRecord> implements Record3<Object, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public void setGeom(Object value) {
        set(0, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public Object getGeom() {
        return get(0);
    }

    /**
     * Setter for <code>public.st_hexagongrid.i</code>.
     */
    public void setI(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.st_hexagongrid.i</code>.
     */
    public Integer getI() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.st_hexagongrid.j</code>.
     */
    public void setJ(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.st_hexagongrid.j</code>.
     */
    public Integer getJ() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Object, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field1() {
        return StHexagongrid.ST_HEXAGONGRID.GEOM;
    }

    @Override
    public Field<Integer> field2() {
        return StHexagongrid.ST_HEXAGONGRID.I;
    }

    @Override
    public Field<Integer> field3() {
        return StHexagongrid.ST_HEXAGONGRID.J;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public Object component1() {
        return getGeom();
    }

    @Override
    public Integer component2() {
        return getI();
    }

    @Override
    public Integer component3() {
        return getJ();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public Object value1() {
        return getGeom();
    }

    @Override
    public Integer value2() {
        return getI();
    }

    @Override
    public Integer value3() {
        return getJ();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    @Override
    public StHexagongridRecord value1(Object value) {
        setGeom(value);
        return this;
    }

    @Override
    public StHexagongridRecord value2(Integer value) {
        setI(value);
        return this;
    }

    @Override
    public StHexagongridRecord value3(Integer value) {
        setJ(value);
        return this;
    }

    @Override
    public StHexagongridRecord values(Object value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StHexagongridRecord
     */
    public StHexagongridRecord() {
        super(StHexagongrid.ST_HEXAGONGRID);
    }

    /**
     * Create a detached, initialised StHexagongridRecord
     */
    public StHexagongridRecord(Object geom, Integer i, Integer j) {
        super(StHexagongrid.ST_HEXAGONGRID);

        setGeom(geom);
        setI(i);
        setJ(j);
    }
}
