/*
 * This file is generated by jOOQ.
 */
package sk.catheaven.model.tables;


import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sk.catheaven.model.Public;
import sk.catheaven.model.tables.records.StHexagongridRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StHexagongrid extends TableImpl<StHexagongridRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.st_hexagongrid</code>
     */
    public static final StHexagongrid ST_HEXAGONGRID = new StHexagongrid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StHexagongridRecord> getRecordType() {
        return StHexagongridRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public final TableField<StHexagongridRecord, Object> GEOM = createField(DSL.name("geom"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "");

    /**
     * The column <code>public.st_hexagongrid.i</code>.
     */
    public final TableField<StHexagongridRecord, Integer> I = createField(DSL.name("i"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.st_hexagongrid.j</code>.
     */
    public final TableField<StHexagongridRecord, Integer> J = createField(DSL.name("j"), SQLDataType.INTEGER, this, "");

    private StHexagongrid(Name alias, Table<StHexagongridRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.DOUBLE),
            DSL.val(null, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""))
        });
    }

    private StHexagongrid(Name alias, Table<StHexagongridRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    /**
     * Create an aliased <code>public.st_hexagongrid</code> table reference
     */
    public StHexagongrid(String alias) {
        this(DSL.name(alias), ST_HEXAGONGRID);
    }

    /**
     * Create an aliased <code>public.st_hexagongrid</code> table reference
     */
    public StHexagongrid(Name alias) {
        this(alias, ST_HEXAGONGRID);
    }

    /**
     * Create a <code>public.st_hexagongrid</code> table reference
     */
    public StHexagongrid() {
        this(DSL.name("st_hexagongrid"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public StHexagongrid as(String alias) {
        return new StHexagongrid(DSL.name(alias), this, parameters);
    }

    @Override
    public StHexagongrid as(Name alias) {
        return new StHexagongrid(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public StHexagongrid rename(String name) {
        return new StHexagongrid(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public StHexagongrid rename(Name name) {
        return new StHexagongrid(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public StHexagongrid call(
          Double size
        , Object bounds
    ) {
        StHexagongrid result = new StHexagongrid(DSL.name("st_hexagongrid"), null, new Field[] {
            DSL.val(size, SQLDataType.DOUBLE),
            DSL.val(bounds, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""))
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public StHexagongrid call(
          Field<Double> size
        , Field<Object> bounds
    ) {
        StHexagongrid result = new StHexagongrid(DSL.name("st_hexagongrid"), null, new Field[] {
            size,
            bounds
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
