/*
 * This file is generated by jOOQ.
 */
package sk.catheaven.model;


import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;

import sk.catheaven.model.tables.StDump;
import sk.catheaven.model.tables.StDumppoints;
import sk.catheaven.model.tables.StDumprings;
import sk.catheaven.model.tables.StHexagongrid;
import sk.catheaven.model.tables.StSquaregrid;
import sk.catheaven.model.tables.StSubdivide;
import sk.catheaven.model.tables.records.StDumpRecord;
import sk.catheaven.model.tables.records.StDumppointsRecord;
import sk.catheaven.model.tables.records.StDumpringsRecord;
import sk.catheaven.model.tables.records.StHexagongridRecord;
import sk.catheaven.model.tables.records.StSquaregridRecord;
import sk.catheaven.model.tables.records.StSubdivideRecord;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StDumpRecord> stDump(
          Configuration configuration
        , Object __1
    ) {
        return configuration.dsl().selectFrom(sk.catheaven.model.tables.StDump.ST_DUMP.call(
              __1
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDump stDump(
          Object __1
    ) {
        return sk.catheaven.model.tables.StDump.ST_DUMP.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDump stDump(
          Field<Object> __1
    ) {
        return sk.catheaven.model.tables.StDump.ST_DUMP.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StDumppointsRecord> stDumppoints(
          Configuration configuration
        , Object __1
    ) {
        return configuration.dsl().selectFrom(sk.catheaven.model.tables.StDumppoints.ST_DUMPPOINTS.call(
              __1
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumppoints stDumppoints(
          Object __1
    ) {
        return sk.catheaven.model.tables.StDumppoints.ST_DUMPPOINTS.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumppoints stDumppoints(
          Field<Object> __1
    ) {
        return sk.catheaven.model.tables.StDumppoints.ST_DUMPPOINTS.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StDumpringsRecord> stDumprings(
          Configuration configuration
        , Object __1
    ) {
        return configuration.dsl().selectFrom(sk.catheaven.model.tables.StDumprings.ST_DUMPRINGS.call(
              __1
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumprings stDumprings(
          Object __1
    ) {
        return sk.catheaven.model.tables.StDumprings.ST_DUMPRINGS.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumprings stDumprings(
          Field<Object> __1
    ) {
        return sk.catheaven.model.tables.StDumprings.ST_DUMPRINGS.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StHexagongridRecord> stHexagongrid(
          Configuration configuration
        , Double size
        , Object bounds
    ) {
        return configuration.dsl().selectFrom(sk.catheaven.model.tables.StHexagongrid.ST_HEXAGONGRID.call(
              size
            , bounds
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StHexagongrid stHexagongrid(
          Double size
        , Object bounds
    ) {
        return sk.catheaven.model.tables.StHexagongrid.ST_HEXAGONGRID.call(
            size,
            bounds
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StHexagongrid stHexagongrid(
          Field<Double> size
        , Field<Object> bounds
    ) {
        return sk.catheaven.model.tables.StHexagongrid.ST_HEXAGONGRID.call(
            size,
            bounds
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StSquaregridRecord> stSquaregrid(
          Configuration configuration
        , Double size
        , Object bounds
    ) {
        return configuration.dsl().selectFrom(sk.catheaven.model.tables.StSquaregrid.ST_SQUAREGRID.call(
              size
            , bounds
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StSquaregrid stSquaregrid(
          Double size
        , Object bounds
    ) {
        return sk.catheaven.model.tables.StSquaregrid.ST_SQUAREGRID.call(
            size,
            bounds
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StSquaregrid stSquaregrid(
          Field<Double> size
        , Field<Object> bounds
    ) {
        return sk.catheaven.model.tables.StSquaregrid.ST_SQUAREGRID.call(
            size,
            bounds
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StSubdivideRecord> stSubdivide(
          Configuration configuration
        , Object geom
        , Integer maxvertices
        , Double gridsize
    ) {
        return configuration.dsl().selectFrom(sk.catheaven.model.tables.StSubdivide.ST_SUBDIVIDE.call(
              geom
            , maxvertices
            , gridsize
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StSubdivide stSubdivide(
          Object geom
        , Integer maxvertices
        , Double gridsize
    ) {
        return sk.catheaven.model.tables.StSubdivide.ST_SUBDIVIDE.call(
            geom,
            maxvertices,
            gridsize
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StSubdivide stSubdivide(
          Field<Object> geom
        , Field<Integer> maxvertices
        , Field<Double> gridsize
    ) {
        return sk.catheaven.model.tables.StSubdivide.ST_SUBDIVIDE.call(
            geom,
            maxvertices,
            gridsize
        );
    }
}
