/*
 * This file is generated by jOOQ.
 */
package sk.catheaven.model;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.conspiracy_theories_seq</code>
     */
    public static final Sequence<Long> CONSPIRACY_THEORIES_SEQ = Internal.createSequence("conspiracy_theories_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.hashtag_conspiracy_theory_seq</code>
     */
    public static final Sequence<Long> HASHTAG_CONSPIRACY_THEORY_SEQ = Internal.createSequence("hashtag_conspiracy_theory_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
