/*
 * This file is generated by jOOQ.
 */
package model;


import model.udt.GeometryDump;
import model.udt.ValidDetail;


/**
 * Convenience access to all UDTs in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>public.geometry_dump</code>
     */
    public static final GeometryDump GEOMETRY_DUMP = model.udt.GeometryDump.GEOMETRY_DUMP;

    /**
     * The type <code>public.valid_detail</code>
     */
    public static final ValidDetail VALID_DETAIL = model.udt.ValidDetail.VALID_DETAIL;
}
